[package]
name = "trdelnik-render-egui"
description = "egui backend implementation for trdelnik-render"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
trdelnik-core = { workspace = true }
trdelnik-render = { workspace = true }
trdelnik-theme = { workspace = true }
egui = { workspace = true }
egui_plot = { workspace = true }
