[package]
name = "trdelnik-data"
description = "Data layer with caching for trdelnik trading charts"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
trdelnik-core = { workspace = true }
trdelnik-render = { workspace = true }
trdelnik-indicators = { workspace = true }
trdelnik-graph = { workspace = true }
trdelnik-script = { workspace = true }
