//! Generic node wrapper for unified indicator handling.
//!
//! This module provides a single `IndicatorNode` that works with any indicator
//! implementing the unified `Indicator` trait. The `InputProvider` trait handles
//! input extraction based on the indicator's `Input` type.
//!
//! # CSE via Hash
//!
//! Instead of `param_signature()`, indicators implement `Hash` and `Eq` on their
//! parameters. The node generates signatures by hashing the indicator state.
//!
//! # Example
//! ```ignore
//! use trdelnik_indicators::Sma;
//! let sma_node = IndicatorNode::with_input(close_id, Sma::new(20));
//! // Signature is automatically generated via hash
//! ```

use std::hash::{Hash, Hasher};
use std::collections::hash_map::DefaultHasher;

use crate::context::ExecutionContext;
use crate::node::{Node, NodeId};
use crate::value::{OutputToValue, Value};
use trdelnik_indicators::{Indicator, Ohlc, Ohlcv};

// ============================================================================
// InputProvider Trait
// ============================================================================

/// Trait for extracting indicator input from execution context and node inputs.
///
/// Implemented for each input type:
/// - `f64` - Extracts from node inputs (requires an input node)
/// - `Ohlc` - Extracts from execution context (no input node needed)
/// - `Ohlcv` - Extracts from execution context (no input node needed)
pub trait InputProvider: Copy {
    /// Extract the input value from context and/or node inputs.
    fn extract(ctx: &ExecutionContext, inputs: &[Value]) -> Option<Self>;

    /// Whether this input type requires a node input.
    /// True for f64, false for Ohlc/Ohlcv which come from context.
    fn requires_node_input() -> bool;
}

impl InputProvider for f64 {
    fn extract(_ctx: &ExecutionContext, inputs: &[Value]) -> Option<Self> {
        inputs.first().and_then(|v| v.as_number())
    }

    fn requires_node_input() -> bool {
        true
    }
}

impl InputProvider for Ohlc {
    fn extract(ctx: &ExecutionContext, _inputs: &[Value]) -> Option<Self> {
        Some(Ohlc::new(ctx.high, ctx.low, ctx.close))
    }

    fn requires_node_input() -> bool {
        false
    }
}

impl InputProvider for Ohlcv {
    fn extract(ctx: &ExecutionContext, _inputs: &[Value]) -> Option<Self> {
        Some(Ohlcv::new(ctx.high, ctx.low, ctx.close, ctx.volume))
    }

    fn requires_node_input() -> bool {
        false
    }
}

// ============================================================================
// IndicatorNode
// ============================================================================

/// Unified node wrapper for any indicator.
///
/// Works with indicators using any input type (f64, Ohlc, Ohlcv) through
/// the `InputProvider` trait.
///
/// # Signature Generation
///
/// The node signature is generated by hashing the indicator's parameters.
/// For indicators with a node input, the input ID is included in the signature.
#[derive(Debug, Clone)]
pub struct IndicatorNode<T: Indicator>
where
    T: Hash + Eq,
    T::Input: InputProvider,
    T::Output: OutputToValue,
{
    input: Option<NodeId>,
    state: T,
}

impl<T: Indicator> IndicatorNode<T>
where
    T: Hash + Eq,
    T::Input: InputProvider,
    T::Output: OutputToValue,
{
    /// Create a node with an input dependency (for f64-input indicators).
    pub fn with_input(input: NodeId, state: T) -> Self {
        Self {
            input: Some(input),
            state,
        }
    }

    /// Create a node without input dependency (for Ohlc/Ohlcv-input indicators).
    pub fn from_context(state: T) -> Self {
        Self { input: None, state }
    }

    /// Get a reference to the indicator state.
    pub fn state(&self) -> &T {
        &self.state
    }

    /// Get a mutable reference to the indicator state.
    pub fn state_mut(&mut self) -> &mut T {
        &mut self.state
    }

    fn compute_hash(&self) -> u64 {
        let mut hasher = DefaultHasher::new();
        self.state.hash(&mut hasher);
        hasher.finish()
    }
}

impl<T: Indicator + Clone + Send + Sync + 'static> Node for IndicatorNode<T>
where
    T: Hash + Eq,
    T::Input: InputProvider,
    T::Output: OutputToValue,
{
    fn signature(&self) -> Option<String> {
        let hash = self.compute_hash();
        match self.input {
            Some(id) => Some(format!("{}:{}:{:x}", T::NAME, id.0, hash)),
            None => Some(format!("{}:{:x}", T::NAME, hash)),
        }
    }

    fn inputs(&self) -> &[NodeId] {
        match &self.input {
            Some(id) => std::slice::from_ref(id),
            None => &[],
        }
    }

    fn reset(&mut self) {
        self.state.reset();
    }

    fn compute(&mut self, ctx: &ExecutionContext, inputs: &[Value]) -> Value {
        let Some(input) = T::Input::extract(ctx, inputs) else {
            return T::Output::to_value(None);
        };

        T::Output::to_value(self.state.next(input))
    }

    fn warmup_period(&self) -> usize {
        self.state.warmup_period()
    }

    fn name(&self) -> &str {
        T::NAME
    }

    fn clone_box(&self) -> Box<dyn Node> {
        Box::new(self.clone())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use trdelnik_indicators::{Atr, Bollinger, Ema, Sma};

    fn create_ctx(close: f64) -> ExecutionContext {
        ExecutionContext::new(0, close, close + 1.0, close - 1.0, close, 1000.0, 0.0)
    }

    #[test]
    fn test_indicator_node_sma() {
        let mut node = IndicatorNode::with_input(NodeId(0), Sma::new(3));

        let result = node.compute(&create_ctx(1.0), &[Value::number(1.0)]);
        assert!(result.is_none());

        let result = node.compute(&create_ctx(2.0), &[Value::number(2.0)]);
        assert!(result.is_none());

        let result = node.compute(&create_ctx(3.0), &[Value::number(3.0)]);
        assert_eq!(result.as_number(), Some(2.0));
    }

    #[test]
    fn test_indicator_node_ema() {
        let mut node = IndicatorNode::with_input(NodeId(0), Ema::new(3));

        node.compute(&create_ctx(1.0), &[Value::number(1.0)]);
        node.compute(&create_ctx(2.0), &[Value::number(2.0)]);
        let result = node.compute(&create_ctx(3.0), &[Value::number(3.0)]);

        assert_eq!(result.as_number(), Some(2.0));
    }

    #[test]
    fn test_indicator_node_bollinger_struct() {
        let mut node = IndicatorNode::with_input(NodeId(0), Bollinger::new(3, 2.0));

        node.compute(&create_ctx(100.0), &[Value::number(100.0)]);
        node.compute(&create_ctx(100.0), &[Value::number(100.0)]);
        let result = node.compute(&create_ctx(100.0), &[Value::number(100.0)]);

        // With constant values, all bands should be 100.0
        assert!(result.is_some());
        let upper = result.get_field("upper").unwrap();
        let middle = result.get_field("middle").unwrap();
        let lower = result.get_field("lower").unwrap();

        assert_eq!(upper.as_number(), Some(100.0));
        assert_eq!(middle.as_number(), Some(100.0));
        assert_eq!(lower.as_number(), Some(100.0));
    }

    #[test]
    fn test_indicator_node_atr() {
        let mut node = IndicatorNode::<Atr>::from_context(Atr::new(3));

        let result = node.compute(&create_ctx(100.0), &[]);
        assert!(result.is_none());

        let result = node.compute(&create_ctx(100.0), &[]);
        assert!(result.is_none());

        let result = node.compute(&create_ctx(100.0), &[]);
        assert!(result.as_number().is_some());
    }

    #[test]
    fn test_indicator_node_signature_with_input() {
        let node = IndicatorNode::with_input(NodeId(5), Sma::new(20));
        let sig = node.signature().unwrap();
        // Signature format: name:input_id:hash
        assert!(sig.starts_with("sma:5:"));
    }

    #[test]
    fn test_indicator_node_signature_without_input() {
        let node = IndicatorNode::<Atr>::from_context(Atr::new(14));
        let sig = node.signature().unwrap();
        // Signature format: name:hash
        assert!(sig.starts_with("atr:"));
        // Should not have input ID format
        assert!(!sig.starts_with("atr:0:") || sig.len() > 6);
    }

    #[test]
    fn test_indicator_node_signature_cse() {
        // Same indicator params should produce same signature
        let node1 = IndicatorNode::with_input(NodeId(5), Sma::new(20));
        let node2 = IndicatorNode::with_input(NodeId(5), Sma::new(20));

        assert_eq!(node1.signature(), node2.signature());

        // Different params should produce different signature
        let node3 = IndicatorNode::with_input(NodeId(5), Sma::new(10));
        assert_ne!(node1.signature(), node3.signature());

        // Different input should produce different signature
        let node4 = IndicatorNode::with_input(NodeId(3), Sma::new(20));
        assert_ne!(node1.signature(), node4.signature());
    }

    #[test]
    fn test_indicator_node_reset() {
        let mut node = IndicatorNode::with_input(NodeId(0), Sma::new(3));

        node.compute(&create_ctx(1.0), &[Value::number(1.0)]);
        node.compute(&create_ctx(2.0), &[Value::number(2.0)]);
        node.compute(&create_ctx(3.0), &[Value::number(3.0)]);

        node.reset();

        let result = node.compute(&create_ctx(10.0), &[Value::number(10.0)]);
        assert!(result.is_none());
    }
}
