[package]
name = "trdelnik-indicators"
description = "Technical indicators for trdelnik trading charts"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
trdelnik-core = { workspace = true }
trdelnik-indicator-derive = { workspace = true }
inventory = { workspace = true }
