[package]
name = "trdelnik-script-bridge"
description = "Glue between trdelnik-script execution results and the chart system"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
trdelnik-core = { workspace = true }
trdelnik-render = { workspace = true }
trdelnik-graph = { workspace = true }
trdelnik-script = { workspace = true }
